# Generated by Django 6.0.2 on 2026-02-17 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('DAY', 'Day'), ('NIGHT', 'Night'), ('OTHER', 'Other')], default='DAY', max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('service_type', models.CharField(choices=[('CLEANING', 'Cleaning'), ('SECURITY', 'Security'), ('MAINTENANCE', 'Maintenance'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('date', models.DateField()),
                ('contact_details', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('precinct', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=255)),
                ('tenant_contact_details', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('tenant',),
            },
        ),
        migrations.CreateModel(
            name='Escalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=50)),
                ('responsible_body', models.CharField(max_length=120)),
                ('email_address', models.EmailField(max_length=254)),
                ('municipality', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=255)),
                ('municipality', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('province', models.CharField(choices=[('WC', 'Western Cape'), ('EC', 'Eastern Cape'), ('NC', 'Northern Cape'), ('FS', 'Free State'), ('KZN', 'KwaZulu-Natal'), ('NW', 'North West'), ('GP', 'Gauteng'), ('MP', 'Mpumalanga'), ('LP', 'Limpopo'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Precinct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('tasks', models.TextField(blank=True)),
                ('service_providers', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=120)),
                ('contact_details', models.TextField(blank=True)),
                ('provider_type', models.CharField(choices=[('COMPANY', 'Company'), ('INDIVIDUAL', 'Individual'), ('MUNICIPAL', 'Municipal'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('activity_log', models.CharField(blank=True, max_length=120)),
                ('precinct', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=100)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('precinct', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('issue_type', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('escalation', models.CharField(blank=True, max_length=120)),
                ('precinct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='core.precinct')),
            ],
            options={
                'ordering': ('-date', '-time'),
                'indexes': [models.Index(fields=['precinct', 'date'], name='core_calllo_precinc_919455_idx'), models.Index(fields=['status', 'date'], name='core_calllo_status_dac9c8_idx')],
            },
        ),
    ]
