# Generated by Django 6.0.2 on 2026-02-17 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calllog',
            name='escalation',
        ),
        migrations.AddField(
            model_name='calllog',
            name='escalation_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='reference_number',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='CallLogSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('precinct_key', models.PositiveIntegerField(db_index=True, default=0)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('date', 'precinct_key')},
            },
        ),
        migrations.CreateModel(
            name='CallLogEscalationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('call_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_events', to='core.calllog')),
            ],
            options={
                'ordering': ('occurred_at',),
                'unique_together': {('call_log', 'level')},
            },
        ),
    ]
