# Generated by Django 6.0.2 on 2026-03-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_due_date_to_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sharepoint_link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
